[serve]
# The address to serve on.
address = "192.168.1.174"
[[hooks]]
stage = "build"
# I'm not sure why we can't just invoke tailwindcss directly, but that doesn't
# seem to work for some reason.
command = "sh"
command_arguments = [
    "-c",
    "npx tailwindcss -i css/tailwind.css -o static/tailwind_compiled.css"
]

