[db]
host = "r-ecipe-s.internal"
port = 5432
user = "r_ecipe_s_user"
database = "r-ecipe-s"
password = "secret"

[http]
port = 8000
host = "[::]"

[search]
port = 80
host = "r-ecipe-s-search.internal"
api_key = "secret"
