version: "3.9"

services:
  r-ecipe-s:
    ports: 
      - "8000:8000"
    build: ./
    command: 
      - sh
      - entrypoint.sh
    environment:
      RUST_LOG: info,tower_http=debug,sqlx=warn
      R_ECIPE_S_DB_PASSWORD: secret123
      R_ECIPE_S_DB_HOST: postgres
      R_ECIPE_S_SERVER_HOST: ${R_ECIPE_S_SERVER_HOST}0.0.0.0
      R_ECIPE_S_SEARCH_API_KEY: secret
      API_KEY: secret123
      R_ECIPE_S_SEARCH_HOST: meilisearch
      R_ECIPE_S_SEARCH_PORT: "7700"
  postgres:
    image: postgres:14.1-alpine3.15
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: r_ecipe_s_user
      POSTGRES_DB: r-ecipe-s
      PGDATA: /pg_data/
    volumes:
      - pg_data:/pg_data
  qdrant:
    image: qdrant/qdrant:v1.6.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  meilisearch:
    image: getmeili/meilisearch:v1.3.5
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: secret
    volumes:
      - meili_data:/data.ms

volumes:
  pg_data: 
  meili_data:
  qdrant_data:
