# fly.toml app configuration file generated for r-ecipe-s-server on 2023-11-01T22:03:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "r-ecipe-s-server"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  RUST_LOG = "INFO,tower_http=debug,sqlx=warn"
  R_ECIPE_S_SEARCH_HOST = "r-ecipe-s-search.internal"
  R_ECIPE_S_VECTOR_SEARCH_HOST = "r-ecipe-s-search.internal"
  R_ECIPE_S_SEARCH_PORT = "7700"
  R_ECIPE_S_SERVER_HOST = "0.0.0.0"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
